apiVersion: v1
kind: Namespace
metadata:
  name: tilines
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyectoweb
  namespace: tilines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyectoweb
  template:
    metadata:
      labels:
        app: proyectoweb
    spec:
      imagePullSecrets:
        - name: ghcr-secret   # ðŸ‘ˆ usamos el secret que creaste
      containers:
        - name: proyectoweb
          image: ghcr.io/angepiedrahita87/proyectoweb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: proyectoweb
  namespace: tilines
spec:
  selector:
    app: proyectoweb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proyectoweb
  namespace: tilines
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  rules:
    - host: proyectoweb.10.43.102.73.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proyectoweb
                port:
                  number: 8080