name: Build and Deploy to MicroK8s

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: proyectoweb
  NAMESPACE: tilines

jobs:
  build-and-push:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Lowercase owner
        shell: bash
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GHCR (root)
        run: |
          echo '${{ secrets.GHCR_TOKEN }}' | sudo docker login ghcr.io -u angepiedrahita87 --password-stdin

      - name: Build Docker image
        run: |
          sudo docker build -t ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest .

      - name: Push Docker image
        run: |
          sudo docker push ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest

  deploy:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Para microk8s no necesitamos KUBECONFIG, usamos su propio kubectl
      - name: Aplicar manifiesto completo (MicroK8s)
        run: |
          sudo microk8s kubectl apply -f k8s/k8s.yaml
