name: Build and Deploy to MicroK8s

on:
  push:
    branches: ["dev"]

env:
  IMAGE_NAME: proyectoweb
  NAMESPACE: tilines

jobs:

  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   # o GHCR_TOKEN

      - name: Build Docker image
        run: docker build -t ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest

  deploy:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar kubectl (MicroK8s)
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Aplicar manifiesto completo
        run: kubectl apply -f k8s.yaml
